Create numpy arrays using initializer

In [ ]:
import numpy as np

#create one dimension array

a1 = np.array([1, 2, 3, 4])
print('a1', a1, a1.shape)

a1 [1 2 3 4] (4,)


In [ ]:
#create two dimensional array

a2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print('a2', a2, a2.shape)

a2 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
# create an array with zero, one, and x

a3 = np.zeros((3, 4))
print('a3', a3, a3.shape)

a4 = np.ones((3, 4))
print('a4', a4, a4.shape)

a5 = np.full((3, 4),2.0)
print('a5', a5, a5.shape)

a3 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
a4 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
a5 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]] (3, 4)


In [ ]:
# create arrays with random floats

a6 = np.random.random((3, 4))
print('a6', a6, a6.shape)

a6 [[0.08437215 0.89212939 0.83846213 0.92826255]
 [0.45886376 0.80514139 0.79401216 0.0982468 ]
 [0.15197835 0.38898683 0.14539412 0.08089856]] (3, 4)


In [ ]:
# create an array with range and shape

a7 = np.arange(200).reshape((-3, 10))
print('a7', a7, a7.shape)

a7 [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]] (20, 10)


In [ ]:
#a2 is the matrxi to play
print('a2', a2, a2.shape)

r1 = a2[1,:]
print('r1', r1, r1.shape)

r2 = a2[1:2, :]
print('r2', r2, r2.shape)

a2 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
r1 [5 6 7 8] (4,)
r2 [[5 6 7 8]] (1, 4)


In [ ]:
r1[0] = 99
print('r1', r1, r1.shape)
print('a2', a2, a2.shape)

r1 [99  6  7  8] (4,)
a2 [[ 1  2  3  4]
 [99  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
list1 = [1, 2, 3, 4]
list2 = list1[:]
print('list1', list1)
print('list2', list2)
list2[0] = 99
print('list1', list1)
print('list2', list2)

list1 [1, 2, 3, 4]
list2 [1, 2, 3, 4]
list1 [1, 2, 3, 4]
list2 [99, 2, 3, 4]


In [ ]:
c1 = a2[:,1]
c2 = a2[:, 1:2]
print('c1', c1, c1.shape)
print('c2', c2, c2.shape)

c1 [ 2  6 10] (3,)
c2 [[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
m1 = a2[1,1]
m2 = a2[1:2, 1:2]
print('m1', m1, m1.shape)
print('m2', m2, m2.shape)

m1 6 ()
m2 [[6]] (1, 1)


In [ ]:
a8 = np.arange(12).reshape((3, 4))
print(a8)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a9 = np.arange(12, 24, 1).reshape((3, 4))
print(a9)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
a10 = a8 + a9
print(a10)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
a11 = a8 - a9
print(a11)

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


In [ ]:
a12 = a8 * a9
a13 = a8 / a9
print(a12)
print(a13)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [ ]:
a14 = a8.dot((a9.T))
print(a14)

[[ 86 110 134]
 [302 390 478]
 [518 670 822]]


In [ ]:
print(a14.min(),a14.max(), a14.min(axis = 0))

86 822 [ 86 110 134]


In [ ]:
a15 = np.arange(10)**3
print(a15)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
i = [1, 2, 4, 8]
print(a15[i])

[  1   8  64 512]


In [ ]:
b = a15 > 20
print(b)

print(a15[b])

[False False False  True  True  True  True  True  True  True]
[ 27  64 125 216 343 512 729]


In [ ]:
c = np.where(a15 > 20)
print(c)

(array([3, 4, 5, 6, 7, 8, 9]),)


Create an array with 100 random floats
• Print the elements > 0.5
• Print the index of elements > 0.5
• Replace the elements < 0.5 to be -1

In [ ]:
e1 = np.random.random(100)
print('e1', e1, e1.shape)

e1 [0.82455684 0.84618333 0.85007033 0.05652252 0.87869797 0.88126654
 0.28890515 0.88024869 0.14741565 0.71464875 0.35072077 0.98330663
 0.37657882 0.68874702 0.18214621 0.71198668 0.09534046 0.92293208
 0.03909067 0.01924602 0.96695888 0.29241187 0.0314471  0.28601804
 0.88466058 0.10802061 0.68065907 0.61755068 0.57660199 0.88115613
 0.20014312 0.50721161 0.79040359 0.20734937 0.00161767 0.15658754
 0.64001102 0.61410536 0.12156549 0.76593358 0.78068953 0.63550623
 0.09675897 0.75491199 0.48366325 0.65162061 0.17614733 0.4773259
 0.34554004 0.42083973 0.35933174 0.13067304 0.97883    0.15403732
 0.36512437 0.25609784 0.97850071 0.3766542  0.28844095 0.56614589
 0.91841234 0.85921436 0.75898826 0.16501338 0.58119792 0.07840049
 0.28111755 0.8358466  0.36712851 0.73181995 0.49973388 0.07987063
 0.42958472 0.66108884 0.14504844 0.6738624  0.02591067 0.79381224
 0.74698818 0.73359755 0.86146404 0.73649148 0.29571222 0.33090219
 0.32302538 0.67868844 0.49046965 0.4937038  0.48502202 0.09

In [ ]:
print(e1[e1 > 0.5])

[0.82455684 0.84618333 0.85007033 0.87869797 0.88126654 0.88024869
 0.71464875 0.98330663 0.68874702 0.71198668 0.92293208 0.96695888
 0.88466058 0.68065907 0.61755068 0.57660199 0.88115613 0.50721161
 0.79040359 0.64001102 0.61410536 0.76593358 0.78068953 0.63550623
 0.75491199 0.65162061 0.97883    0.97850071 0.56614589 0.91841234
 0.85921436 0.75898826 0.58119792 0.8358466  0.73181995 0.66108884
 0.6738624  0.79381224 0.74698818 0.73359755 0.86146404 0.73649148
 0.67868844 0.88492002 0.56871539 0.55925823 0.61099788 0.95042081]


In [ ]:
print(np.where(e1> 0.5))

(array([ 0,  1,  2,  4,  5,  7,  9, 11, 13, 15, 17, 20, 24, 26, 27, 28, 29,
       31, 32, 36, 37, 39, 40, 41, 43, 45, 52, 56, 59, 60, 61, 62, 64, 67,
       69, 73, 75, 77, 78, 79, 80, 81, 85, 91, 92, 93, 95, 96]),)


In [ ]:
e1[e1 <0.5] = -1
print(e1)

[ 0.82455684  0.84618333  0.85007033 -1.          0.87869797  0.88126654
 -1.          0.88024869 -1.          0.71464875 -1.          0.98330663
 -1.          0.68874702 -1.          0.71198668 -1.          0.92293208
 -1.         -1.          0.96695888 -1.         -1.         -1.
  0.88466058 -1.          0.68065907  0.61755068  0.57660199  0.88115613
 -1.          0.50721161  0.79040359 -1.         -1.         -1.
  0.64001102  0.61410536 -1.          0.76593358  0.78068953  0.63550623
 -1.          0.75491199 -1.          0.65162061 -1.         -1.
 -1.         -1.         -1.         -1.          0.97883    -1.
 -1.         -1.          0.97850071 -1.         -1.          0.56614589
  0.91841234  0.85921436  0.75898826 -1.          0.58119792 -1.
 -1.          0.8358466  -1.          0.73181995 -1.         -1.
 -1.          0.66108884 -1.          0.6738624  -1.          0.79381224
  0.74698818  0.73359755  0.86146404  0.73649148 -1.         -1.
 -1.          0.67868844 -1.      

In [ ]:
e3 = np.random.randint(0, 100, (100))
print(e3)

[65 49 39 62 84 54 71 58 93 86 74 77 20 96 18 99 25 55 13 69  2 69 35  4
 75 77 11 65 76 16 67 82 16 37 11  8 55 74 84  1 92 62 83 51 77 59 24 38
 47 61 26 87 67 23 21 84 68 58 70 19 82 78 44  7 90  6 18 63 50 21 96 39
 45 87 94  2 23 32 75 65 16 59 53 47 68 57 15 23 57 22 69 91 64  9 10 60
 21 59 59 30]


In [ ]:
print(e3.min(), e3.max())

1 99


In [ ]:
min = e3.min()
max = e3.max()
e4 = (e3 - min) / (max - min)
print(e4)

[0.65306122 0.48979592 0.3877551  0.62244898 0.84693878 0.54081633
 0.71428571 0.58163265 0.93877551 0.86734694 0.74489796 0.7755102
 0.19387755 0.96938776 0.17346939 1.         0.24489796 0.55102041
 0.12244898 0.69387755 0.01020408 0.69387755 0.34693878 0.03061224
 0.75510204 0.7755102  0.10204082 0.65306122 0.76530612 0.15306122
 0.67346939 0.82653061 0.15306122 0.36734694 0.10204082 0.07142857
 0.55102041 0.74489796 0.84693878 0.         0.92857143 0.62244898
 0.83673469 0.51020408 0.7755102  0.59183673 0.23469388 0.37755102
 0.46938776 0.6122449  0.25510204 0.87755102 0.67346939 0.2244898
 0.20408163 0.84693878 0.68367347 0.58163265 0.70408163 0.18367347
 0.82653061 0.78571429 0.43877551 0.06122449 0.90816327 0.05102041
 0.17346939 0.63265306 0.5        0.20408163 0.96938776 0.3877551
 0.44897959 0.87755102 0.94897959 0.01020408 0.2244898  0.31632653
 0.75510204 0.65306122 0.15306122 0.59183673 0.53061224 0.46938776
 0.68367347 0.57142857 0.14285714 0.2244898  0.57142857 0.2142857

In [ ]:
e4 = np.random.randint(0, 100, (100))
print(e4)

[36 78 71 50 15 79  4 27 23 98 23 31 15 50 89 17 93 40  7 16 93 85 94  6
  6 37 70 63 76 95  9 24 66 58 53 21 91 31 47 21 28 61 58 85 70 90 10 70
 70  3 62 52  1 99 61 86 21 41 90 84 12 60  2 15 57 11 43  2 79  6 44 56
  9 25 83 77 76 85 56 76  1 74 60 40 29 64 40 86 10 93 80 85 91  7 63 13
 64  0 37 41]


In [ ]:
print(np.percentile(e4, [25, 50, 75]))

[21.   52.5  76.25]
